//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmartDemo.rc
//
#define IDD_SMARTDEMO_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_VIDEO_DIALOG                129
#define IDD_VIDEOWND                    130
#define IDD_PARAM_DIALOG                131
#define IDD_RECOG_DIALOG                132
#define IDD_DIALOG1                     133
#define IDD_ADDPHOTO_DIALOG             133
#define IDD_DIALOG2                     134
#define IDD_FINDPHOTO_DIALOG            134
#define IDD_PHOTODETAIL_DIALOG          135
#define IDD_FINDRECOG_DIALOG            137
#define IDD_RECOGDETAIL_DIALOG          138
#define IDD_RECOG_V2_DIALOG             139
#define IDD_RECOGDETAIL_SCENE_DLG       140
#define IDD_ALARMLINKAGE_DIALOG         141
#define IDD_RECOG_V5_DIALOG             142
#define IDB_BITMAP1                     146
#define IDB_BITMAP2                     147
#define IDB_PNG1                        148
#define IDB_BITMAP3                     149
#define IDB_PNG2                        153
#define IDC_IPADDRESS1                  1000
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_VIDEO_WIN                   1003
#define IDC_EDIT_NAME                   1003
#define IDC_CLARITY_EDIT                1003
#define IDC_STATIC_WNDALL               1004
#define IDC_FRONTAL_EDIT                1004
#define ID_LOGOUT                       1005
#define ID_LOGIN                        1006
#define IDC_PIC_SNAP                    1007
#define IDC_PIC_STD                     1008
#define IDC_STATIC_PER                  1009
#define IDC_STATIC_SNAP_TEXT            1010
#define IDC_STATIC_STD_TEXT             1011
#define IDC_BUTTON_OPENVIDEO            1012
#define IDC_BUTTON_CLOSEVIDEO           1013
#define IDC_BUTTON_PARAM                1014
#define IDC_TAB_PARAM                   1015
#define IDC_EDIT_POLICY                 1016
#define IDC_EDIT_SNAPINTERVAL           1017
#define IDC_EDIT_SNAPTHRESHOLD          1018
#define IDC_EDIT_COMPTHRESHOLD          1019
#define IDC_EDIT_SPEED                  1020
#define IDC_EDIT_SNAPCOUNT              1021
#define IDC_DATETIMEPICKER_BIRTHDAY     1022
#define IDC_COMBO_CITY                  1023
#define IDC_COMBO_GENDER                1024
#define IDC_COMBO_PROVINCE              1025
#define IDC_COMBO_CERTTYPE              1026
#define IDC_BUTTON_ADDFACE              1027
#define IDC_BUTTON_IMPORT               1028
#define IDC_EDIT_CERTNUMBER             1029
#define IDC_EDIT_OTHER                  1030
#define IDC_STATIC_FACE                 1031
#define IDD_SAVE_BUTTON                 1032
#define IDC_EDIT_FIND_FACE_NAME         1033
#define IDC_COMBO_FIND_FACE_GENDER      1034
#define IDC_COMBO_FIND_FACE_PROV        1035
#define IDC_COMBO_FIND_FACE_CITY        1036
#define IDC_COMBO_FIND_FACE_CERTTYPE    1037
#define IDC_DATETIMEPICKER_FIND_FACE_BEGIN 1038
#define IDC_DATETIMEPICKER_FIND_FACE_END 1039
#define IDC_BTN_FIND_FACE_FIND          1040
#define IDC_BTN_FIND_FACE_RESET         1041
#define IDC_LIST_FIND_FACE              1042
#define IDC_EDIT_FIND_FACE_CERT         1043
#define IDC_BTN_FACE_DEL                1044
#define IDC_BTN_VIEW_FACE               1045
#define IDC_STATIC_DETAIL_GENDER        1047
#define IDC_STATIC_DETAIL_BIRTH         1048
#define IDC_STATIC_DETAIL_PROV          1049
#define IDC_STATIC_DETAIL_CITY          1050
#define IDC_STATIC_DETAIL_CERTTYPE      1051
#define IDC_STATIC_DETAIL_CERTNO        1052
#define IDC_STATIC_DETAIL_MEMO          1053
#define IDOK_DETAIL_MODIFY              1054
#define IDC_STATIC_FACE_DETAIL_PHOTO    1055
#define IDC_EDIT_FACE_DETAIL_NAME       1056
#define IDC_DATETIMEPICKER1             1057
#define IDC_DATETIMEPICKER2             1058
#define IDC_DATETIMEPICKER3             1059
#define IDC_DATETIMEPICKER4             1060
#define IDC_BUTTON_FINDRECOG            1061
#define IDC_LISTFIND_RECOG              1062
#define IDC_BUTTON_FIND_RECOG_DETAIL    1063
#define IDC_STATIC_SNAP_PIC             1064
#define IDC_STATIC_MATCH_FACE1          1065
#define IDC_STATIC_MATCH_FACE2          1066
#define IDC_STATIC_MATCH_FACE3          1067
#define IDC_STATIC_MATCH_FACE4          1068
#define IDC_STATIC_MATCH_FACE5          1069
#define IDC_STATIC_RECOG_DETAIL_TIME    1070
#define IDC_STATIC_RECOG_DETAIL_NAME    1071
#define IDC_STATIC_RECOG_DETAIL_GENDER  1072
#define IDC_STATIC_RECOG_DETAIL_PROV    1073
#define IDC_STATIC_RECOG_DETAIL_CITY    1074
#define IDC_STATIC_RECOG_DETAIL_BIRTH   1075
#define IDC_STATIC_RECOG_DETAIL_CERTTYPE 1076
#define IDC_STATIC_RECOG_DETAIL_CERTNO  1077
#define IDC_STATIC_RECOG_DETAIL_CMPVALUE 1078
#define IDC_STATIC_RECOG_DETAIL_FACE2_CMPVALUE 1079
#define IDC_STATIC_RECOG_DETAIL_FACE3_CMPVALUE 1080
#define IDC_STATIC_RECOG_DETAIL_FACE4_CMPVALUE 1081
#define IDC_STATIC_RECOG_DETAIL_FACE5_CMPVALUE 1082
#define IDC_CHECK_FINDRECOG_USE_THRESH  1083
#define IDC_STATIC_SDK_VERSION          1084
#define IDC_STATIC_BATCHIMPORT_PROGRESS 1085
#define IDC_STATIC_IPC_VERSION          1085
#define IDC_SIMILARITY_EDIT             1086
#define IDC_STATIC__VERSION3            1086
#define IDC_STATIC_MODE_VERSION         1086
#define IDC_DET_EDIT                    1087
#define IDC_BUTTON_EXPORT_FACE_LIB      1088
#define IDC_BUTTON_SYNC_FACE_LIB        1089
#define IDC_STATIC_EXPORT_FACE_LIB_PROGRESS 1090
#define IDC_STATIC_SYNC_FACE_LIB_PROGRESS 1091
#define IDC_BUTTON_IMPORT_FROM_DIR      1092
#define IDC_COMBO_LIB_INDEX             1093
#define IDC_BUTTON_VIEW_SCENE           1094
#define IDC_STATIC_SCENE_JPG            1095
#define IDC_BTN_EXPORT_RECOG_HTML       1096
#define IDC_STATIC_EXPORT_RECOG_PROGRESS 1097
#define IDC_CHECK_ALARM1                1098
#define IDC_CHECK_ALARM2                1099
#define IDC_CHECK_ALARMSOUND            1100
#define IDC_DATETIMEPICKER_BEGIN1       1101
#define IDC_DATETIMEPICKER_END1         1102
#define IDC_DATETIMEPICKER_BEGIN2       1103
#define IDC_BUTTON1                     1103
#define IDC_BUTTON_REGISTER             1103
#define IDC_BTN_FACE_DEL_ALL            1103
#define IDC_BUTTON_DEL_ALL_RECOG        1103
#define IDC_DATETIMEPICKER_END2         1104
#define IDC_SIMI_V5_EDIT                1104
#define IDC_DATETIMEPICKER_BEGIN3       1105
#define IDC_DET_V5_EDIT                 1105
#define IDC_DATETIMEPICKER_END3         1106
#define IDC_MFCEDITBROWSE1              1106
#define IDC_DATETIMEPICKER_BEGIN4       1107
#define IDC_ANH                         1107
#define IDC_DATETIMEPICKER_END4         1108
#define IDC_DATETIMEPICKER_BEGIN5       1109
#define IDC_DATETIMEPICKER_END5         1110
#define IDC_DATETIMEPICKER_BEGIN6       1111
#define IDC_DATETIMEPICKER_END6         1112
#define IDC_DATETIMEPICKER_BEGIN7       1113
#define IDC_DATETIMEPICKER_END7         1114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
